version: '3'

# TODO: consider adding a script for filling the DB with mock testing data

services:
  postgres:
    image: postgres:12.2  # TODO: [LATER] switch to -alpine
    environment:
      POSTGRES_USER: homework
      POSTGRES_PASSWORD: DazBMyGQdKqKG  # FIXME: remember to chg passwd before deploying to PROD
      POSTGRES_DB: users_db
      PGDATA: /data/postgres
    volumes:
      - users_data:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  users_data:
