version: '3'

# TODO: consider adding a script for filling the DB with mock testing data

services:

  users_db:
    image: postgres:12.2  # TODO: [LATER] switch to -alpine
    environment:
      POSTGRES_USER: homework
      POSTGRES_PASSWORD: DazBMyGQdKqKG  # FIXME: remember to chg passwd before deploying to PROD
      POSTGRES_DB: users_db
      PGDATA: /data/postgres
    volumes:
      - users_data:/data/postgres
    # ports:
    #   - "5432:5432"
    restart: unless-stopped

  users_rest:
    build: .
    image: users-rest:dev
    # environment:
      # FIXME: postgres params
    ports:
      - "8080:8080"
    depends_on:
      - users_db
    volumes:
      # TODO: do we want below volume?
      - users_logs:/log
    # TODO: capture stdout & stderr to some central logger?
    restart: unless-stopped

volumes:
  users_data:
  users_logs:
